name: CI # 워크플로우의 이름

on: [push, pull_request] # 어떤 GitHub 이벤트에 워크플로우를 실행할 지 정의

jobs:
  build: # 작업의 이름
    runs-on: ubuntu-latest # 실행할 환경

    steps: # 워크플로우의 단계
    - uses: actions/checkout@v2 # 저장소의 코드를 체크아웃

    - name: Use Node.js 19.6.0 # 이름 정의
      uses: actions/setup-node@v1 # Node.js를 설정
      with:
        node-version: 19.6.0 # Node.js의 버전 정의

    - name: Install dependencies # 이름 정의
      run: npm ci # 의존성 설치

    - name: Start Application # 'Build' 대신 'Start Application'으로 변경
      run: npm start # 'npm run build' 대신 'npm start'로 변경

    - name: Test # 이름 정의
      run: npm run test # 테스트 실행