name: CI # Workflow name

on: [push, pull_request] # Run workflow on push or pull_request events.

jobs: 
  build: 
    runs-on: ubuntu-latest # Specifies the environment where the workflow runs.

    steps: # Steps that the workflow will execute.
    - uses: actions/checkout@v2 # Checks out the repository.

    - name: Use Node.js 19.6.0
      uses: actions/setup-node@v1 # Sets up Node.js.
      with:
        node-version: 19.6.0

    - name: Install dependencies
      run: npm ci # Installs dependencies.

    - name: Build
      run: npm run build # Builds the project.

    - name: Test
      run: npm run test # Runs tests.